# Generated by Django 2.1.7 on 2019-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste_app', '0002_auto_20190214_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='delete_after_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paste',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
